services:
  promtail-agent:
    image: grafana/promtail:2.9.8
    container_name: soc-promtail
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
    volumes:
      - /var/log:/var/log:ro
      - wazuh-logs:/var/ossec/logs:ro # Read from shared volume
      - ./promtail.yml:/etc/promtail/promtail.yml:ro
      - promtail-data:/tmp
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - soc-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: soc-node-exporter
    restart: unless-stopped
    pid: host
    network_mode: host
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M
    volumes:
      - /proc:/host/proc:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /:/rootfs:ro,rslave
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  wazuh-agent:
    image: wazuh/wazuh-agent:4.9.0
    container_name: soc-wazuh-agent
    restart: unless-stopped
    environment:
      - WAZUH_MANAGER=${WAZUH_MANAGER_IP:-192.168.1.206}
      - WAZUH_AGENT_NAME=${AGENT_NAME:-soc-agent-container}
    volumes:
      - wazuh-logs:/var/ossec/logs
      - /etc/os-release:/etc/os-release:ro # Help agent detect OS
    networks:
      - soc-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
  soc-dashboard:
    build: ./dashboard
    container_name: soc-dashboard
    restart: unless-stopped
    ports:
      - "8080:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - soc-net

volumes:
  promtail-data:
  wazuh-logs:


networks:
  soc-net:
    driver: bridge
